In [13]:
import numpy as np

a= np.array([[1,2,3,],[4,5,6]])
print(a.ndim)
print(a.shape)
print(a.size)
print(a.dtype)
print(a.itemsize)
print(a.data)

2
(2, 3)
6
int64
8


In [86]:
a=np.ndarray((2,2))
b=np.array([1.2,3.5,5.1])
print(a)
print(b)

[[4.9e-324 4.4e-323]
 [4.9e-324 2.5e-323]]
[1.2 3.5 5.1]


In [20]:
c= np.array([[1,2],[3,4]], dtype=complex) 
print(c)

[[1.+0.j 2.+0.j]
 [3.+0.j 4.+0.j]]


In [34]:
print(np.zeros((3,4))
b= np.ones((2,3,4), dtype=np.int16)
print(b)



[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]

[[[1 1 1 1]
  [1 1 1 1]
  [1 1 1 1]]

 [[1 1 1 1]
  [1 1 1 1]
  [1 1 1 1]]]
[[1.39069238e-309 1.39069238e-309 1.39069238e-309]
 [1.39069238e-309 1.39069238e-309 1.39069238e-309]]


In [37]:
np.empty((2,3),end="")

SyntaxError: unexpected character after line continuation character (1697398507.py, line 1)

In [39]:
np.arange(10,30,5)

array([10, 15, 20, 25])

In [41]:
np.arange(0,2,0.3) # np.arange(n,m,x) n과 m 사이를 x 만큼 계속 더해서 출력


array([0. , 0.3, 0.6, 0.9, 1.2, 1.5, 1.8])

In [43]:
np.linspace(0,2,9) # np.linspace (n,m,x) n부터 m 까지 x개로 나눔

array([0.  , 0.25, 0.5 , 0.75, 1.  , 1.25, 1.5 , 1.75, 2.  ])

In [45]:
np.arange(12) # 0부터 입력한 n-1 까지 

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [55]:
b=np.arange(12).reshape(4,3) # reshape 개수 안맞으면 오류 
print(b)

c =np.arange(24).reshape(4,3,2) # reshape 개수 안맞으면 오류 
print(c)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
[[[ 0  1]
  [ 2  3]
  [ 4  5]]

 [[ 6  7]
  [ 8  9]
  [10 11]]

 [[12 13]
  [14 15]
  [16 17]]

 [[18 19]
  [20 21]
  [22 23]]]


In [61]:
x= np.arange(10)
print(x)
print(x[2])
print(x[-8])

[0 1 2 3 4 5 6 7 8 9]
2
2


In [63]:
x.shape=(2,5) # 2행 5열로 만듬 
print(x[1,3])
print(x[1,-1])

8
9


In [66]:
print(x[0])
print(x[0][2]) # 2,3번째 코드 출력값 같음
print(x[0,2]) 

[0 1 2 3 4]
2
2


In [72]:
a= np.array([[1,2,3],
             [4,5,6],
             [7,8,9]])

print(a)
print(a[[0,1,2,0],[0,2,0,1]])

b= np.array([0,2,0,1])
print(a[b,b])
print()

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[1 6 7 2]
1 [1, 2] [2, 0] [0, 1]
[1 9 1 5]



In [80]:
x=np.arange(10)
print(x[2:5])
print(x[:-7]) # 뒤에 7개 짜르겠다 
print(x[1:7:2]) # 1에서 7 까지 2간격으로 출력 
y=np.arange(35).reshape(5,7)

print(y[1:5:2])
print(y[1:5:2,::3])

[2 3 4]
[0 1 2]
[1 3 5]
[[ 7  8  9 10 11 12 13]
 [21 22 23 24 25 26 27]]
[[ 7 10 13]
 [21 24 27]]


In [87]:
a=np.array(range(6)).reshape(2,3)
print(a[a>2])

[3 4 5]


In [98]:
a=np.array(range(1,13)).reshape(3,4)
print(a)

b=a[:2]
print(b)

c=a[:,1:3]
print(c)

b[0,0]= -1
print(a)

d=a[:,1:3]
print(d)

e=c+d
print(e) # 행열이 일치하면 연산 가능 


[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[[1 2 3 4]
 [5 6 7 8]]
[[ 2  3]
 [ 6  7]
 [10 11]]
[[-1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[[ 2  3]
 [ 6  7]
 [10 11]]
[[ 4  6]
 [12 14]
 [20 22]]


In [101]:
a=np.array(range(1,13)).reshape(3,4)
print(a)

b= np.copy(a[:2])
print(b)

b[0,0]=-1
print(b)

print(a)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[[1 2 3 4]
 [5 6 7 8]]
[[-1  2  3  4]
 [ 5  6  7  8]]
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [104]:
a=np.floor(10*np.random.random((3,4)))
print(a)

[[4. 5. 1. 3.]
 [2. 0. 8. 1.]
 [9. 6. 7. 2.]]


In [114]:
print(a.shape)
print(a.ravel()) # 1차원으로 바꿔버림
print(a.reshape(6,2))
print(a.T) # 가로와 세로 바뀜 (3행 4열 , 4행 3열) 

(3, 4)
[4. 5. 1. 3. 2. 0. 8. 1. 9. 6. 7. 2.]
[[4. 5.]
 [1. 3.]
 [2. 0.]
 [8. 1.]
 [9. 6.]
 [7. 2.]]
[[4. 2. 9.]
 [5. 0. 6.]
 [1. 8. 7.]
 [3. 1. 2.]]


In [118]:
print(a)
a.resize((2,6))
print(a)
print(a.reshape(3,-1)) # -1을 넣으면 앞에 3행만 해서 알아서 계산

[[4. 5. 1. 3. 2. 0.]
 [8. 1. 9. 6. 7. 2.]]
[[4. 5. 1. 3. 2. 0.]
 [8. 1. 9. 6. 7. 2.]]
[[4. 5. 1. 3.]
 [2. 0. 8. 1.]
 [9. 6. 7. 2.]]


In [124]:
a=np.floor(10*np.random.random((2,2)))
b=np.floor(10*np.random.random((2,2)))
print(a)
print(b)

print(np.vstack((a,b))) # 행열에 밑에 갖다 붙임 ()

print(np.hstack((a,b))) # 행열에 오른쪽 편에 갖다 붙임 

[[1. 6.]
 [1. 3.]]
[[0. 5.]
 [2. 2.]]
[[1. 6.]
 [1. 3.]
 [0. 5.]
 [2. 2.]]
[[1. 6. 0. 5.]
 [1. 3. 2. 2.]]


In [128]:
a=np.floor(10*np.random.random(12)).reshape(2,6)
print(a)
print(np.hsplit(a,3)) # 행열 왼쪽 오른쪽으로 나눠짐 

print(np.vsplit(a,2)) # 행열 위아래로 나눠줌 

[[6. 5. 4. 8. 7. 1.]
 [0. 5. 2. 1. 0. 2.]]
[array([[6., 5.],
       [0., 5.]]), array([[4., 8.],
       [2., 1.]]), array([[7., 1.],
       [0., 2.]])]
[array([[6., 5., 4., 8., 7., 1.]]), array([[0., 5., 2., 1., 0., 2.]])]


In [142]:
a= np.ones((5,5))
b= np.zeros((5,5))

a[1:4,1:4]=0
print(a)

b[1:4,1:4]=1
print(b)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]
[[0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0.]]


In [169]:
a= np.ones((8,8))
print(a)
a[0:7:2,0:7:2]=0
a[1:8:2,1:8:2]=0
print(a)

[[1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1.]]
[[0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]]


In [188]:
a=np.array([180,72,172,66,162,60,167,53,176,80,155,60,177,77,130,40])
b=a.reshape(2,4,2)
print(b)

[[[180  72]
  [172  66]
  [162  60]
  [167  53]]

 [[176  80]
  [155  60]
  [177  77]
  [130  40]]]


In [193]:
a=np.array([20,30,40,50])
b= np.arange(4)
10*np.sin(a) 

array([ 9.12945251, -9.88031624,  7.4511316 , -2.62374854])

In [199]:
b=np.arange(12).reshape(3,4)
b.sum(axis=0) # 위, 아래로 다 더함 
b.min(axis=1) # 왼, 오른쪽 모든 수 중 가장 작은 수  

b.cumsum(axis=1) # 누적해서 더한 값 왼쪽에서 오른쪽으로  
b.cumsum(axis=0) # 누적해서 더한 값 위에서 아래로 

array([[ 0,  1,  2,  3],
       [ 4,  6,  8, 10],
       [12, 15, 18, 21]])

In [201]:
B= np.arange(3)
np.exp(B)

array([1.        , 2.71828183, 7.3890561 ])

In [202]:
np.sqrt(B)

array([0.        , 1.        , 1.41421356])

In [228]:
x=np.array(range(1,13)).reshape(4,3)
print(x, end="/n/n")
v=np.array([1,0,1])
y=np.empty_like(x)
print(y,end="\n\n")
for i in range(len(x)):
    y[i,:] = x[i,:]+v
print(y)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]/n/n[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]

[[ 2  2  4]
 [ 5  5  7]
 [ 8  8 10]
 [11 11 13]]


In [229]:
x=np.array(range(1,13)).reshape(4,3)
print(x, end="\n\n")
v=np.array([1,0,1])
y=x+v
print(y)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]

[[ 2  2  4]
 [ 5  5  7]
 [ 8  8 10]
 [11 11 13]]


In [231]:
a=np.array([[0],[1],[2]])
print(a)
b=np.arange(3)
print(b)
print(a+b)

[[0]
 [1]
 [2]]
[0 1 2]
[[0 1 2]
 [1 2 3]
 [2 3 4]]


In [232]:
# 실습 4 

def linear_system_solver(ndarr,v) :
    return np.linalg.inv(ndarr)@v


a= np.array([1,1,2,1]).reshape(2,2)
b= np.array([15,25]).reshape(2,1)
print(linear_system_solver(a,b))


[[10.]
 [ 5.]]


In [251]:
# 실습 5
data=np.random.rand(4,6).round(1)
print(data)
print()
length=np.array([4,1,6,3])
length=np.expand_dims(length,1)
maxlen= data.shape[1]
idx=np.arange(maxlen)
idx=np.tile(idx,(4,1))
print(idx)
print()
mask = idx < length
print(mask)
print()
data[~mask]=float('-inf')
print(data)

[[0.6 0.  0.4 0.4 0.8 0.6]
 [0.7 0.4 0.8 0.6 0.2 0. ]
 [0.3 0.6 0.2 0.3 0.4 0.8]
 [0.3 0.4 0.5 0.5 0.3 1. ]]

[[0 1 2 3 4 5]
 [0 1 2 3 4 5]
 [0 1 2 3 4 5]
 [0 1 2 3 4 5]]

[[ True  True  True  True False False]
 [ True False False False False False]
 [ True  True  True  True  True  True]
 [ True  True  True False False False]]

[[ 0.6  0.   0.4  0.4 -inf -inf]
 [ 0.7 -inf -inf -inf -inf -inf]
 [ 0.3  0.6  0.2  0.3  0.4  0.8]
 [ 0.3  0.4  0.5 -inf -inf -inf]]


array([[15, 30],
       [25, 25]])

In [214]:
x= np.array([[15],[25]])
x

array([[15],
       [25]])